apiVersion: nextdns.jacaudi.io/v1alpha1
kind: Profile
metadata:
  name: test-profile
  namespace: crossplane-system
spec:
  name: test
  apiKeySecret: 
    name: nextdns-api-key
    namespace: crossplane-system
    key: api-key
  privacy:
    disguisedTrackers: true
    allowAffiliate: false
    blocklists:
      - oisd
      - steven-black
      - easyprivacy
      - hagezi-multi-pro
    natives:
      - windows
      - apple
      - samsung
      - xiaomi
      - huawei
      - alexa
      - roku
      - sonos
  security:
    threatIntelligenceFeeds: true
    aiThreatDetection: true
    googleSafeBrowsing: true
    cryptojacking: true
    dnsRebinding: false
    idnHomographs: true
    typosquatting: true
    dga: true
    nrd: true
    ddns: true
    parking: true
    csam: true
    tlds:
      - ru
      - ch
      - pizza
  parentalControl:
    safeSearch: false
    youtubeRestrictedMode: true
  allowlist:
    - mixpanel.com
    - newrelic.com
    - mailchimp.com
    - hulu.com
  denylist:
    - accuweather.com